"""Repository protocol interfaces."""
from __future__ import annotations

from typing import Protocol


class ContactRepositoryProtocol(Protocol):
    async def append(self, record: dict) -> None: ...
    async def update(self, request_id: str, updates: dict) -> None: ...
    async def count(self) -> int: ...


class IdempotencyRepositoryProtocol(Protocol):
    def body_hash(self, payload: dict) -> str: ...
    async def get(self, key: str, body_hash: str) -> dict | None: ...
    async def put(self, key: str, body_hash: str, response: dict) -> None: ...


class MetricsRepositoryProtocol(Protocol):
    async def snapshot(self) -> dict: ...
    async def record_circuit_open(self) -> None: ...
    async def mark_email_queued(self, request_id: str) -> None: ...
